#!/bin/bash
#
### File managed by Puppet
#
if [ "$IFACE" = "eth0.4000" ] || [ "$IFACE" = "--all" ]; then
  if ip route show  table vswitch | grep -qP "1.2.3.57 "
  then
    ip route del 1.2.3.57/32 dev eth0.4000 table vswitch
  fi
  if ip route show  table vswitch | grep -qP "0.0.0.0/0|default "
  then
    ip route del 0.0.0.0/0 via 1.2.3.57 dev eth0.4000 table vswitch
  fi
fi

